### ISSUE TITLE
Only integer values read?

### ISSUE THREAD

**Issue by dmelgar** [bertmelis/DHT#7]
The spec state 8 bit integer value and 8 bit decimal value, yet the only values returned from the examples return integer values as floats with no fractional component.

Is this a configuration option or is this library not parsing the full 40 bit data response?

**Comment by bertmelis** [comment]
It depends if you define your sensor as DHT11, then no decimals will be returned, as the sensor's accuracy is not up to decimal level.

Change your sensor to type DHT22 and it'll work. (or there's a bug somewhere)

For example:
comment out https://github.com/bertmelis/DHT/blob/master/examples/Callback/Callback.ino#L34
and enable https://github.com/bertmelis/DHT/blob/master/examples/Callback/Callback.ino#L35

**Comment by bertmelis** [comment]
Did it work?
